spring:
  datasource:
    url: jdbc:postgresql://www.dreammm.net:25432/postgres?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.heyoufu.pay: debug
    com.heyoufu.pay.demo.service: debug
