server:
  port: 8301

spring:
  application:
    name: pay-merchant
  profiles:
    active: dev
  # redis配置
  redis:
    database: 2
    host: www.dreammm.net
    port: 26379
    password: Az741
  main:
    allow-bean-definition-overriding: true
jackson:
  date-format: yyyy-MM-dd HH:mm:ss
  time-zone: GMT+8
# mybatis配置
mybatis:
  type-aliases-package: com.heyoufu.pay.model,com.heyoufu.merchant.vo
  mapper-locations: classpath*:mapper/*.xml
feign:
  hystrix:
    enabled: true   #打开Feign自带的断路器

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always


