spring:
  datasource:
    url: jdbc:mysql://localhost:3306/minishop?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  data:
    elasticsearch:
      cluster-nodes: 127.0.0.1:9300
      cluster-name: elasticsearch
  elasticsearch:
    rest:
      uris: http://localhost:9200
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.heyoufu.pay: debug   # 需要根据实际情况修正
