eureka:
  client:
    service-url:
      defaultZone: http://pay-register:8001/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true



auth:
  host: http://pay-authserver
  # 服务端口号
  port: 9000
  # 也 可以 通过 配置中心 进行配置
