eureka:
  client:
    service-url:
      defaultZone: http://pay-register:8001/eureka/
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:postgresql://www.dreammm.net:25432/hefutong
    username: postgres
    password: Az123..

  cloud:
    config:
      profile: prod #启用环境名称
      label: master #分支名称
      name: agent #配置文件名称
      discovery:
        enabled: true
        service-id: pay-config


auth:
  host: localhost
  # 服务端口号
  port: 9000
