server:
  host: localhost
  # 服务端口号
  port: 9000
spring:
  # 服务名
  application:
    name: pay-auth-server
  # 全局时间日期格式配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 选择运行环境
  profiles:
    active: dev
# mybatis配置
mybatis:
  type-aliases-package: com.heyoufu.pay.model
  mapper-locations: classpath*:mapper/*.xml
# sql打印
logging:
  level:
    com.heyoufu.pay.mapper: debug