eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
    registry-fetch-interval-seconds: 10
    instance:
      prefer-ip-address: true

spring:
  # 数据库配置
  datasource:
    url: jdbc:postgresql://192.168.1.230:25432/hefutong
    username: postgres
    password: Az123..

auth:
  host: localhost
  # 服务端口号
  port: 9000
